import type { ComponentType } from "react"

export interface GuideMeta {
  slug: string
  title: string
  description: string
  category: "키워드 분석" | "블로그 SEO" | "콘텐츠 마케팅" | "실전 활용"
  date: string  // YYYY-MM-DD
  author: string
  readingMinutes: number
}

export const guides: GuideMeta[] = [
  { slug: "keyword-search-volume", title: "키워드 검색량이란? 초보자를 위한 완벽 가이드", description: "키워드 검색량의 의미와 블로그 운영에 활용하는 법을 알려드립니다.", category: "키워드 분석", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "keyword-competition", title: "블로그 키워드 경쟁도 분석하는 법", description: "경쟁도 지표를 이해하고 진입 가능한 키워드를 찾는 방법을 설명합니다.", category: "키워드 분석", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "saturation-index", title: "포화지수로 블루오션 키워드 찾는 방법", description: "포화지수의 개념과 저경쟁 키워드 발굴 전략을 소개합니다.", category: "키워드 분석", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 4 },
  { slug: "long-tail-keywords", title: "롱테일 키워드 전략: 검색량 적어도 수익 나는 이유", description: "롱테일 키워드의 장점과 활용 방법을 정리합니다.", category: "키워드 분석", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "keyword-grade", title: "키워드 등급(S~D)의 의미와 활용법", description: "옵티써치 키워드 등급 시스템을 설명하고 실전 활용법을 안내합니다.", category: "키워드 분석", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 4 },
  { slug: "blog-title-tips", title: "블로그 제목 작성법: 클릭률 높이는 7가지 공식", description: "검색 상위 노출과 클릭을 부르는 제목 작성 노하우 7가지.", category: "블로그 SEO", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 7 },
  { slug: "seo-basics", title: "블로그 SEO 기초: 검색 상위 노출의 원리", description: "검색 엔진 최적화의 기본 원리와 블로그에 적용하는 방법.", category: "블로그 SEO", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 7 },
  { slug: "heading-tags", title: "블로그 글 구조 잡는 법: H2/H3 태그 활용", description: "제목 태그를 활용한 구조적 글쓰기로 SEO 점수를 올리는 방법.", category: "블로그 SEO", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 4 },
  { slug: "content-length", title: "블로그 본문 길이, 몇 글자가 적당할까?", description: "SEO에 유리한 콘텐츠 분량을 통계와 사례로 알아봅니다.", category: "블로그 SEO", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 4 },
  { slug: "meta-description", title: "메타 디스크립션 작성법: 검색 결과 클릭을 부르는 요약문", description: "CTR을 높이는 메타 디스크립션 작성 원칙을 정리합니다.", category: "블로그 SEO", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 4 },
  { slug: "seasonal-keywords", title: "시즌 키워드 활용법: 트렌드 분석으로 타이밍 잡기", description: "계절성 키워드를 미리 발굴하고 콘텐츠 타이밍을 맞추는 전략.", category: "콘텐츠 마케팅", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-monetization", title: "블로그 수익화 전략: 애드센스부터 체험단까지", description: "블로그로 돈을 버는 주요 방법 5가지와 각각의 장단점.", category: "콘텐츠 마케팅", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 7 },
  { slug: "ai-writing-tools", title: "AI 글쓰기 도구 활용법: 효율적인 블로그 운영", description: "AI 도구를 활용해 블로그 생산성을 높이는 실전 팁.", category: "콘텐츠 마케팅", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-category", title: "블로그 카테고리 구성 전략", description: "SEO와 사용성을 모두 잡는 카테고리 설계 원칙.", category: "콘텐츠 마케팅", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 4 },
  { slug: "content-calendar", title: "콘텐츠 캘린더 만드는 법: 월간 발행 계획 수립", description: "꾸준한 발행을 위한 콘텐츠 캘린더 구축 방법.", category: "콘텐츠 마케팅", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 4 },
  { slug: "optisearch-keyword-tutorial", title: "옵티써치로 키워드 분석하는 방법 (튜토리얼)", description: "옵티써치 키워드 분석기의 모든 기능을 스텝별로 안내합니다.", category: "실전 활용", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 7 },
  { slug: "optisearch-title-tutorial", title: "옵티써치 AI 제목 생성기 활용 가이드", description: "AI 제목 생성기 사용법과 고품질 결과를 얻는 프롬프트 팁.", category: "실전 활용", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "keyword-to-publish", title: "키워드 분석부터 글 발행까지: 실전 워크플로우", description: "키워드 발굴, 글쓰기, 발행까지 이어지는 블로그 운영 전체 흐름.", category: "실전 활용", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 7 },
  { slug: "competitor-analysis", title: "경쟁 블로그 분석하고 차별화하는 방법", description: "상위 노출 블로그를 분석하고 차별화 포인트를 찾는 방법.", category: "실전 활용", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "first-blog-post", title: "블로그 첫 글 쓰기: 주제 선정부터 발행까지", description: "블로그를 막 시작한 사람을 위한 첫 포스팅 가이드.", category: "실전 활용", date: "2026-04-16", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-side-job-guide", title: "직장인 블로그 부업 시작 가이드: 첫 6개월 로드맵", description: "직장인이 퇴근 후 1시간으로 블로그 부업을 시작해 6개월 안에 토대를 만드는 단계별 실전 가이드입니다.", category: "실전 활용", date: "2026-04-29", author: "옵티써치 팀", readingMinutes: 7 },
  { slug: "find-blog-keywords-free", title: "블로그 키워드 찾는 법: 무료 도구로 시작하는 3단계 발굴법", description: "네이버 자동완성, 광고 시스템, 데이터랩을 활용해 비용 없이 블로그 키워드를 발굴하는 3단계 방법과 실전 키워드 선정 기준을 정리합니다.", category: "키워드 분석", date: "2026-04-30", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-seo-score-check", title: "블로그 SEO 점수 측정하는 법: 지금 당장 내 블로그를 진단하는 방법", description: "내 블로그의 SEO 상태를 스스로 진단하는 방법을 단계별로 정리합니다. 서치어드바이저, 구글 서치콘솔, 수동 체크리스트까지 지금 바로 점검할 수 있는 실전 가이드입니다.", category: "블로그 SEO", date: "2026-05-01", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-write-faster", title: "블로그 글 빨리 쓰는 법: 1시간 안에 완성하는 5단계 루틴", description: "바쁜 직장인도 퇴근 후 1시간 안에 블로그 글을 완성할 수 있습니다. 기획부터 발행까지 글쓰기 속도를 높이는 5단계 실전 루틴과 반복 사용 가능한 템플릿 전략을 정리합니다.", category: "콘텐츠 마케팅", date: "2026-05-02", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-adsense-approval", title: "블로그 애드센스 승인 받는 법: 첫 신청부터 통과까지 실전 체크리스트", description: "블로그 애드센스 승인을 처음 신청하는 초보자를 위해 콘텐츠 기준, 탈락 원인 5가지, 재신청 주의사항, 최종 체크리스트까지 실전 중심으로 단계별 정리합니다.", category: "실전 활용", date: "2026-05-04", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-keyword-extraction-sites", title: "블로그 키워드 추출 사이트 비교: 무료와 유료의 차이는?", description: "블로그 키워드 추출에 활용할 수 있는 도구들을 기능별로 비교하고, 무료 도구와 유료 도구를 단계별로 선택하는 기준을 정리합니다.", category: "키워드 분석", date: "2026-05-05", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "naver-blog-top-exposure", title: "네이버 블로그 상위 노출 방법: 검색 1페이지에 오르는 7가지 핵심 전략", description: "네이버 블로그 상위 노출에 영향을 주는 C-RANK, 키워드 제목, 본문 구조, 이미지, 발행 주기 등 7가지 핵심 전략을 초보 블로거 기준으로 정리합니다.", category: "블로그 SEO", date: "2026-05-06", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-fill-1000-characters", title: "블로그 글 1000자 채우는 법: 내용 없어도 분량 늘리는 5가지 실전 방법", description: "블로그 글 1000자가 막막할 때 쓸 수 있는 5가지 방법을 소개합니다. 소제목 분리, 예시 추가, Q&A 섹션 등 초보도 바로 적용 가능한 분량 확장 전략을 정리합니다.", category: "콘텐츠 마케팅", date: "2026-05-07", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-keyword-search-volume-check", title: "블로그 키워드 검색량 조회 방법: 네이버에서 무료로 확인하는 4단계", description: "네이버 광고 시스템을 활용해 블로그 키워드 검색량을 직접 조회하는 방법을 4단계로 정리합니다. 계정 생성부터 데이터 해석까지 초보도 따라할 수 있는 실전 가이드입니다.", category: "키워드 분석", date: "2026-05-08", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-seo-checklist", title: "블로그 SEO 체크리스트: 발행 전 반드시 확인할 10가지 항목", description: "블로그 글 발행 전 확인해야 할 SEO 체크리스트를 정리합니다. 제목 키워드, 메타 디스크립션, 이미지 alt 텍스트, 내부 링크까지 초보 블로거도 바로 적용할 수 있는 실전 점검 목록입니다.", category: "블로그 SEO", date: "2026-05-09", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-experience-group-guide", title: "블로그 체험단 신청 가이드: 초보도 선정되는 5가지 핵심 전략", description: "블로그 체험단을 처음 신청하는 초보 블로거를 위해 신청 조건, 선정 확률을 높이는 신청서 작성법, 발행 시 주의사항까지 단계별로 정리합니다.", category: "실전 활용", date: "2026-05-11", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-content-ideas", title: "블로그 글감 떠올리는 법: 아이디어가 떨어졌을 때 쓰는 5가지 방법", description: "블로그 글감이 떨어졌을 때 바로 쓸 수 있는 5가지 아이디어 발굴법을 정리합니다. 검색어 자동완성, 커뮤니티 질문, 메모 습관까지 초보도 적용 가능한 방법을 소개합니다.", category: "콘텐츠 마케팅", date: "2026-05-12", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "naver-datalab-guide", title: "네이버 데이터랩 활용법: 블로그 콘텐츠 기획에 바로 쓰는 실전 가이드", description: "네이버 데이터랩에서 키워드 추이와 계절성을 확인하는 방법을 정리합니다. 검색어 트렌드, 시즌 키워드 발굴, 발행 타이밍 최적화까지 블로그 콘텐츠 기획에 바로 적용할 수 있는 실전 활용법을 소개합니다.", category: "키워드 분석", date: "2026-05-13", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-meta-tag-guide", title: "블로그 메타태그 설정 가이드: SEO를 결정하는 핵심 태그 5가지", description: "블로그 SEO에서 빠질 수 없는 메타태그의 종류와 각각 올바르게 설정하는 방법을 초보 블로거 기준으로 정리합니다.", category: "블로그 SEO", date: "2026-05-14", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-writing-with-ai", title: "AI로 블로그 글쓰기 실전: 처음부터 발행까지 한 번에 끝내는 4단계 방법", description: "AI를 활용해 블로그 글을 처음부터 발행까지 완성하는 실전 방법을 4단계로 정리합니다. 키워드 선정, 개요 작성, 섹션별 생성, 퇴고까지 초보도 따라할 수 있는 구체적인 전략을 소개합니다.", category: "콘텐츠 마케팅", date: "2026-05-15", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-traffic-growth-tips", title: "블로그 유입 늘리는 현실적인 방법: 오늘 바로 적용하는 5가지 전략", description: "블로그 방문자가 늘지 않는 이유와 해결책을 정리합니다. 키워드 선정, 발행 주기, 내부 링크, 외부 채널까지 초보 블로거가 바로 실천할 수 있는 유입 증가 전략 5가지를 소개합니다.", category: "실전 활용", date: "2026-05-16", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-inflow-keyword-analysis", title: "블로그 유입 키워드 분석 방법: 어떤 검색어로 방문자가 들어오는지 파악하는 3가지 방법", description: "블로그에 어떤 키워드로 방문자가 유입되는지 파악하는 방법을 정리합니다. 네이버 서치어드바이저, 구글 서치콘솔, 블로그 통계를 활용한 실전 분석법을 소개합니다.", category: "키워드 분석", date: "2026-05-17", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-search-not-showing", title: "블로그 검색 노출 안 되는 이유 7가지: 원인별 해결법 정리", description: "블로그 글을 써도 검색에 노출되지 않는 이유 7가지를 정리합니다. 인덱싱 누락부터 경쟁도 오판까지 초보 블로거가 자주 겪는 원인과 단계별 해결 방법을 안내합니다.", category: "블로그 SEO", date: "2026-05-18", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-writing-block-solutions", title: "블로그 글 안 써질 때 쓰는 5가지 실전 해결법", description: "블로그 글이 안 써지는 이유 3가지를 파악하고 즉시 적용할 수 있는 해결법 5가지를 정리합니다. 완벽주의, 글감 부재, 의욕 저하별 맞춤 전략으로 꾸준한 발행을 이어가는 방법을 안내합니다.", category: "콘텐츠 마케팅", date: "2026-05-19", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-monetization-roadmap", title: "블로그 수익화 단계별 로드맵: 초보도 따라갈 수 있는 5단계 현실 전략", description: "블로그로 처음 수익을 내고 싶지만 어디서부터 시작해야 할지 모르는 초보 블로거를 위해 애드센스, 체험단, 협찬까지 수익화 단계를 순서대로 정리합니다.", category: "실전 활용", date: "2026-05-20", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "keyword-saturation-guide", title: "키워드 포화도란 무엇인가: 의미부터 블로그 실전 활용까지", description: "키워드 포화도의 개념과 포화지수 활용법을 이해하고 내 블로그 수준에 맞는 키워드를 선정하는 방법을 정리합니다.", category: "키워드 분석", date: "2026-05-21", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-bounce-rate-reduce", title: "블로그 이탈률 줄이는 법: 방문자를 붙잡는 5가지 실전 전략", description: "블로그 이탈률의 의미와 높은 이탈률이 검색 노출에 미치는 영향을 설명하고, 방문자가 글을 읽고 페이지를 떠나지 않도록 붙잡는 5가지 실전 전략을 정리합니다.", category: "블로그 SEO", date: "2026-05-27", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-ranking-check-sites", title: "블로그 순위 확인 사이트 추천: 내 글이 몇 위인지 확인하는 4가지 방법", description: "블로그 글이 검색 결과 몇 위에 있는지 확인하는 방법과 무료로 사용할 수 있는 순위 확인 사이트를 정리합니다. 네이버 서치어드바이저, 구글 서치콘솔 활용법까지 단계별로 안내합니다.", category: "실전 활용", date: "2026-05-28", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-writing-template", title: "블로그 글쓰기 템플릿 모음: 초보도 바로 쓰는 5가지 구성 패턴", description: "블로그 글을 쓸 때 구조가 없어서 막히는 초보 블로거를 위해 정보 나열형, 문제-해결형, 경험 후기형 등 바로 적용 가능한 5가지 글쓰기 템플릿과 상황별 활용 기준을 정리합니다.", category: "콘텐츠 마케팅", date: "2026-05-29", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-keyword-trend-analysis", title: "블로그 키워드 트렌드 보는 법: 상승 키워드를 미리 잡는 4가지 방법", description: "블로그 키워드 트렌드를 분석해 검색 수요가 늘어나기 전에 미리 글을 발행하는 방법을 정리합니다. 네이버 데이터랩, 자동완성 활용, 계절성 패턴까지 실전 위주로 안내합니다.", category: "키워드 분석", date: "2026-05-30", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "google-search-console-blog-guide", title: "구글 서치콘솔 블로그 활용법: 검색 성과를 데이터로 파악하는 4가지 방법", description: "구글 서치콘솔을 블로그에 연동하고 검색 성과를 분석하는 방법을 정리합니다. 클릭 수, 노출 수, 순위 데이터 해석부터 개선 우선순위 결정까지 실전 위주로 안내합니다.", category: "블로그 SEO", date: "2026-05-31", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-side-job-time-management", title: "직장인 블로그 부업 시간 관리법: 퇴근 후 1시간으로 꾸준히 쓰는 5단계 전략", description: "직장인 블로거가 퇴근 후 제한된 시간 안에 블로그를 꾸준히 운영하는 시간 관리법을 정리합니다. 루틴화, 배치 작업, 현실적 목표 설정까지 실전 전략 5가지를 소개합니다.", category: "실전 활용", date: "2026-06-01", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-stats-guide", title: "블로그 통계 보는 법: 방문자·유입·체류시간을 읽는 3가지 기준", description: "블로그 통계에서 방문자 수, 유입 키워드, 체류시간 데이터를 올바르게 읽는 방법을 정리합니다. 주 1회 확인 루틴부터 통계를 콘텐츠 전략으로 연결하는 방법까지 실전 위주로 안내합니다.", category: "키워드 분석", date: "2026-06-02", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-indexing-not-working", title: "블로그 인덱싱 안 될 때: 원인 5가지와 즉시 적용하는 해결법", description: "블로그 글을 발행했는데 검색에 잡히지 않는 인덱싱 문제의 원인 5가지와 서치어드바이저·수동 크롤링 요청 등 바로 적용할 수 있는 해결법을 정리합니다.", category: "블로그 SEO", date: "2026-06-03", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "chatgpt-blog-tips", title: "ChatGPT 블로그 활용 노하우: 글쓰기 시간을 절반으로 줄이는 5가지 방법", description: "ChatGPT를 블로그 글쓰기에 활용해 시간을 절약하는 5가지 실전 방법을 정리합니다. 주제 발굴, 개요 작성, 본문 생성, 퇴고까지 초보도 바로 적용할 수 있는 프롬프트 활용법과 주의사항을 안내합니다.", category: "콘텐츠 마케팅", date: "2026-06-04", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-how-to-start", title: "블로그 처음 시작하는 법: 첫날 결정해야 할 5가지 핵심", description: "블로그를 처음 시작하는 초보자를 위해 플랫폼 선택, 주제 설정, 이름 결정, 첫 글 주제, 발행 주기까지 첫날 반드시 정해야 할 5가지 결정을 단계별로 정리합니다.", category: "실전 활용", date: "2026-06-05", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "keyword-competition-check", title: "블로그 키워드 경쟁도 보는 법: 내 수준에 맞는 키워드를 고르는 4가지 기준", description: "블로그 키워드를 선택할 때 경쟁도를 올바르게 판단하는 방법을 정리합니다. 경쟁도 지표, 상위 노출 글 분석, 포화지수 활용까지 초보 블로거 기준으로 안내합니다.", category: "키워드 분석", date: "2026-06-06", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-dwell-time-tips", title: "블로그 체류시간 늘리는 법: 방문자가 더 오래 머무르는 5가지 실전 전략", description: "블로그 체류시간이 낮으면 검색 노출에도 영향을 줍니다. 방문자가 페이지를 떠나지 않고 글을 끝까지 읽도록 유도하는 5가지 실전 전략을 정리합니다.", category: "블로그 SEO", date: "2026-06-07", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-body-structure-tips", title: "블로그 본문 구조 잡는 법: 읽기 쉬운 글을 만드는 5단계 구성 전략", description: "블로그 본문을 체계적으로 구성하는 방법을 정리합니다. 도입-본문-마무리 흐름과 소제목 배치, 단락 분리까지 초보 블로거도 바로 적용할 수 있는 5단계 구성 전략을 안내합니다.", category: "콘텐츠 마케팅", date: "2026-06-08", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-first-100-visitors", title: "블로그 첫 100명 방문자 모으기: 초보도 한 달 안에 달성하는 5가지 방법", description: "블로그를 시작하고 첫 방문자 100명을 만드는 것이 가장 막막한 단계입니다. 롱테일 키워드 공략, 커뮤니티 공유, 발행 주기 유지까지 초보 블로거가 한 달 안에 첫 100명을 달성하는 실전 방법 5가지를 정리합니다.", category: "실전 활용", date: "2026-06-09", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "naver-seo-guide-2026", title: "네이버 SEO 가이드 2026: 블로그 상위 노출을 위한 핵심 전략 총정리", description: "2026년 기준 네이버 SEO 핵심 원리와 블로그 상위 노출 전략을 정리합니다. C-RANK, 다이아 로직, 키워드 최적화부터 실전 체크리스트까지 초보 블로거도 바로 적용할 수 있는 가이드입니다.", category: "블로그 SEO", date: "2026-06-10", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-visitor-analysis", title: "블로그 방문자 수 분석 방법: 데이터로 성장 전략을 세우는 4가지 기준", description: "블로그 방문자 수 데이터를 올바르게 읽고 성장 전략으로 연결하는 방법을 정리합니다. 유입 키워드, 인기 게시글, 방문 패턴 분석까지 초보 블로거도 바로 실천할 수 있는 실전 가이드입니다.", category: "키워드 분석", date: "2026-06-11", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-sponsored-review-tips", title: "블로그 협찬 받는 법: 초보 블로거도 신청 가능한 5가지 실전 방법", description: "블로그 협찬을 처음 받고 싶은 초보 블로거를 위해 협찬 플랫폼 활용법, 선정 조건, 신청서 작성 팁까지 바로 실천할 수 있는 실전 방법 5가지를 정리합니다.", category: "실전 활용", date: "2026-06-12", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-vs-youtube-side-job", title: "블로그 vs 유튜브 부업 비교: 직장인에게 더 맞는 선택은?", description: "블로그와 유튜브 부업의 진입 장벽, 초기 수익화 시간, 시간 투자 효율을 직장인 관점에서 실질적으로 비교합니다. 어느 쪽을 먼저 시작할지 기준을 잡고 싶은 초보 부업러를 위한 가이드입니다.", category: "콘텐츠 마케팅", date: "2026-06-15", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-sudden-traffic-drop", title: "블로그 노출 갑자기 줄었을 때: 원인 5가지와 빠른 회복 방법", description: "블로그 유입이 갑자기 줄어든 이유를 원인별로 분석하고 즉시 대응할 수 있는 방법을 정리합니다. 업데이트, 저품질, 경쟁글 진입까지 5가지 원인과 단계별 해결법을 안내합니다.", category: "블로그 SEO", date: "2026-06-15", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-side-job-tax-guide", title: "블로그 부업 세금 정리: 직장인이 꼭 알아야 할 소득 신고 기본 가이드", description: "블로그 수익이 생기면 세금 처리가 막막한 직장인을 위해 기타소득과 사업소득 구분, 종합소득세 신고 방법, 필요경비 처리까지 기본 사항을 정리합니다.", category: "실전 활용", date: "2026-06-16", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-posting-frequency", title: "블로그 일주일에 몇 개 써야 할까: 발행 빈도와 상위 노출의 관계", description: "블로그 발행 주기가 검색 노출에 미치는 영향과 초보 블로거에게 맞는 현실적인 주당 발행 횟수를 정리합니다. 지속 가능한 루틴을 만드는 방법까지 안내합니다.", category: "블로그 SEO", date: "2026-06-17", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-ad-revenue-structure", title: "블로그 광고 수익 구조 이해: 애드센스·체험단·협찬 수익이 만들어지는 원리", description: "블로그 수익이 어떤 구조로 발생하는지 이해하면 수익화 전략이 명확해집니다. 애드센스 CPC·CPM 원리부터 체험단·협찬 수익 흐름까지 초보 블로거를 위해 정리합니다.", category: "콘텐츠 마케팅", date: "2026-06-18", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-topic-selection", title: "블로그 주제 정하는 법: 오래 쓸 수 있는 주제를 고르는 4가지 기준", description: "블로그 주제를 정하지 못해 시작을 미루는 초보 블로거를 위해, 지속 가능한 주제를 선택하는 4가지 기준과 주제별 장단점을 실전 중심으로 정리합니다.", category: "실전 활용", date: "2026-06-19", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-low-quality-checklist", title: "블로그 저품질 의심 체크리스트: 지금 당장 확인해야 할 10가지 신호", description: "블로그 유입이 줄거나 검색 노출이 안 될 때 저품질을 가장 먼저 의심하게 됩니다. 콘텐츠·기술 영역으로 나뉜 10가지 체크리스트로 내 블로그 상태를 직접 진단하는 방법을 안내합니다.", category: "블로그 SEO", date: "2026-06-20", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-side-job-100-monthly", title: "블로그 부업 월 100만원 가능할까: 현실적인 수익 단계와 달성 조건", description: "블로그 부업으로 월 100만원을 달성할 수 있는지, 어떤 조건과 기간이 필요한지 현실적인 수익 흐름과 전략을 정리합니다.", category: "실전 활용", date: "2026-06-21", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-nickname-tips", title: "블로그 닉네임 정하는 법: 검색과 신뢰를 동시에 잡는 5가지 기준", description: "블로그 닉네임은 첫인상이자 브랜딩의 출발점입니다. 검색에 잘 걸리고 기억에 남으면서 전문성도 전달하는 닉네임을 정하는 5가지 실전 기준과 흔한 실수를 정리합니다.", category: "실전 활용", date: "2026-06-23", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-photo-source-guide", title: "블로그 사진 출처 표기 가이드: 저작권 위반 없이 이미지를 쓰는 4가지 방법", description: "블로그에 이미지를 사용할 때 출처 표기 방법을 모르면 저작권 위반이 될 수 있습니다. 저작권 걱정 없이 이미지를 활용하고 올바르게 출처를 표기하는 4가지 실전 방법을 정리합니다.", category: "콘텐츠 마케팅", date: "2026-06-24", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-trust-recovery", title: "블로그 신뢰도 회복 방법: 떨어진 검색 신뢰도를 되살리는 5가지 전략", description: "블로그 신뢰도가 낮아지면 검색 노출과 방문자 수가 동시에 줄어듭니다. 신뢰도 저하 원인을 파악하고 단계별로 회복하는 5가지 실전 방법을 정리합니다.", category: "블로그 SEO", date: "2026-06-25", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-citation-guide", title: "블로그 인용 표기 방법: 저작권 걱정 없이 출처를 다는 4가지 원칙", description: "블로그에 통계·기사·전문가 발언을 인용할 때 출처를 올바르게 표기하는 4가지 원칙을 정리합니다. 저작권 분쟁 없이 참고 자료를 활용하고 독자 신뢰도를 높이는 실전 방법을 안내합니다.", category: "콘텐츠 마케팅", date: "2026-06-26", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-duplicate-content-avoidance", title: "블로그 글 복사 의심 받을 때 대처법: 중복 콘텐츠 문제를 피하는 5가지 방법", description: "블로그 글이 복사본으로 의심받으면 검색 노출에 직접적인 타격이 생깁니다. 중복 콘텐츠 판정을 피하고 원본 인정을 받는 5가지 실전 방법을 정리합니다.", category: "블로그 SEO", date: "2026-06-27", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-one-year-review", title: "블로그 1년 운영 후기: 직장인 부업러가 배운 5가지 현실 교훈", description: "블로그를 1년 운영하면서 직장인 부업러가 실제로 겪는 변화와 배운 교훈 5가지를 정리합니다. 초반 실수부터 통계 활용, 수익화 타이밍까지 현실 중심으로 안내합니다.", category: "실전 활용", date: "2026-06-28", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-post-deletion-effects", title: "블로그 글 삭제하면 어떻게 될까: SEO에 미치는 영향과 올바른 대처법", description: "블로그 글을 삭제하면 검색 노출과 도메인 신뢰도에 실제로 어떤 영향이 생기는지 정리합니다. 삭제 전 반드시 확인해야 할 SEO 체크리스트와 대안 방법까지 안내합니다.", category: "블로그 SEO", date: "2026-06-29", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-backup-guide", title: "블로그 백업 방법: 글·이미지·설정을 잃지 않는 4가지 실전 전략", description: "블로그를 오랫동안 운영할수록 글·이미지·설정 손실 위험도 커집니다. 플랫폼 장애, 계정 해킹, 실수 삭제에 대비해 지금 바로 적용할 수 있는 백업 방법 4가지를 단계별로 정리합니다.", category: "실전 활용", date: "2026-06-30", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-post-editing-tips", title: "블로그 글 수정 시 주의점: SEO를 지키면서 글을 고치는 4가지 원칙", description: "블로그 글 수정이 잘못되면 기존 검색 순위가 사라질 수 있습니다. URL 변경 금지, 핵심 키워드 유지, 재인덱싱 요청까지 SEO를 해치지 않고 글을 고치는 4가지 원칙을 정리합니다.", category: "콘텐츠 마케팅", date: "2026-07-01", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "start-blog-for-free", title: "블로그 무료로 시작하기: 초기 비용 없이 첫 글까지 완성하는 5단계 가이드", description: "블로그를 시작하고 싶지만 비용이 걱정이라면 안심해도 됩니다. 무료 플랫폼과 도구만으로 블로그를 개설하고 첫 글을 발행하는 5단계 실전 방법을 정리합니다.", category: "실전 활용", date: "2026-07-02", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-first-page-entry-tips", title: "블로그 첫 페이지 진입 안 될 때: 검색 1페이지를 막는 5가지 원인과 해결법", description: "블로그 글을 써도 검색 첫 페이지에 오르지 못하는 5가지 원인을 분석합니다. 키워드 경쟁도 오판, 콘텐츠 완성도, 도메인 신뢰도까지 즉시 적용 가능한 해결 전략을 정리합니다.", category: "블로그 SEO", date: "2026-07-03", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-category-examples", title: "블로그 카테고리 구성 예시: 주제별 실전 설계법과 흔한 실수 3가지", description: "블로그 카테고리를 어떻게 나눠야 할지 막막한 초보자를 위해 부업·음식·육아·여행 등 주제별 카테고리 구성 예시와 설계 원칙을 정리합니다.", category: "콘텐츠 마케팅", date: "2026-07-04", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-search-exclusion-fix", title: "블로그 검색 누락 해결: 내 글이 검색에서 사라졌을 때 확인하는 5가지 체크포인트", description: "블로그 글이 어느 날 갑자기 검색 결과에서 사라졌다면 원인을 단계별로 점검해야 합니다. 인덱싱 오류, 저품질 판정, 경쟁 글 진입까지 누락 원인 5가지와 각각의 해결 방법을 정리합니다.", category: "블로그 SEO", date: "2026-07-05", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "blog-income-reporting-guide", title: "블로그 수익 신고 방법: 홈택스로 직접 하는 종합소득세 신고 5단계", description: "블로그 수익이 생겼을 때 홈택스에서 직접 종합소득세를 신고하는 방법을 5단계로 정리합니다. 기타소득과 사업소득 구분, 신고 기간, 필요경비 처리까지 처음 신고하는 직장인을 위한 실전 가이드입니다.", category: "실전 활용", date: "2026-07-06", author: "옵티써치 팀", readingMinutes: 6 },
  { slug: "naver-blog-indexing-acceleration", title: "네이버 블로그 인덱싱 빠르게 하는 법: 새 글을 검색에 빨리 잡히게 하는 4가지 방법", description: "블로그 글을 발행해도 검색에 바로 잡히지 않는다면 인덱싱 속도를 높여야 합니다. 서치어드바이저 수집 요청부터 RSS 등록, 내부 링크 연결까지 네이버 인덱싱을 가속하는 4가지 실전 방법을 정리합니다.", category: "블로그 SEO", date: "2026-07-07", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-first-post-writing", title: "블로그 첫 글 쓰는 법: 처음 발행하는 사람이 알아야 할 5가지 원칙", description: "블로그 첫 글을 어떻게 시작해야 할지 막막한 초보 블로거를 위해 주제 선정, 키워드 설정, 글 구조, 제목 작성, 발행 후 점검까지 처음부터 올바르게 시작하는 5가지 원칙을 정리합니다.", category: "콘텐츠 마케팅", date: "2026-07-08", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-keyword-placement-tips", title: "블로그 키워드 넣는 위치: 제목·본문·태그까지 SEO 효과를 높이는 5가지 원칙", description: "블로그 글에서 키워드를 어디에, 몇 번 넣어야 SEO에 효과적인지 정리합니다. 제목, 도입부, 소제목, 본문, 메타태그까지 키워드 배치 원칙 5가지를 초보 블로거 기준으로 안내합니다.", category: "키워드 분석", date: "2026-07-10", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-follower-growth-tips", title: "블로그 이웃 늘리는 법: 처음 1000명까지 빠르게 모으는 5가지 방법", description: "블로그 이웃이 늘수록 초기 유입과 댓글 반응이 쌓이고 검색 노출에도 긍정적인 신호가 됩니다. 신규 블로거가 처음 이웃 1000명을 만드는 5가지 실전 방법을 정리합니다.", category: "실전 활용", date: "2026-07-11", author: "옵티써치 팀", readingMinutes: 5 },
  { slug: "blog-internal-link-strategy", title: "블로그 내부 링크 전략: SEO 점수를 높이는 4가지 연결 방법", description: "블로그 내부 링크가 검색 노출과 체류시간에 미치는 영향과 링크 구조를 올바르게 설계하는 4가지 실전 방법을 정리합니다.", category: "블로그 SEO", date: "2026-07-12", author: "옵티써치 팀", readingMinutes: 5 },
]

export const guideMap = new Map(guides.map(g => [g.slug, g]))

export function getGuideBySlug(slug: string): GuideMeta | undefined {
  return guideMap.get(slug)
}

export function getGuidesByCategory(category: GuideMeta["category"]): GuideMeta[] {
  return guides.filter(g => g.category === category)
}
